steps:

  - command: |-
      echo "~~~ pip install"
      echo 'odus' | sudo -S rm -rf /tmp/pip_build_root/*
      echo 'odus' | sudo -S pip install -r requirements.txt

      echo "~~~ test app"
      python -m unittest discover tests

    label: application test
    agents:
      - type=native

  - command: |-
      echo "~~~ clear cache"
      echo 'odus' | sudo -S rm -rf /tmp/pip_build_root/*

      echo '~~~ update pip'
      pip install virtualenv
      pip install virtualenvwrapper
      source /usr/local/bin/virtualenvwrapper.sh
      mkvirtualenv binlog-analyser

      echo "~~~ install requirements"
      pip install --upgrade pip setuptools wheel

      echo "~~~ building dist"
      echo 'odus' | sudo -S pip install -r requirements.txt
      rm -rf dist/*
      python setup.py sdist

      echo "~~~ testing dist"
      echo '1'
      version=$(cat binlogexplorer/version)
      echo '2'
      pip --version
      echo '3'
      pip uninstall mysql-binlog-explorer -y || true
      echo '4'
      pip install dist/mysql-binlog-explorer-${version}.tar.gz --no-cache-dir
      echo '5'
      mysql-binlog-explorer -h
      echo '6'

    label: package distribution test
    agents:
      - type=native

  - wait

  - command: |-
      echo "~~~ pip install"
      echo 'odus' | sudo -S rm -rf /tmp/pip_build_root/*
      echo 'odus' | sudo -S pip install -r requirements_ci.txt

      echo '~~~ update pip'
      python -m pip install --upgrade pip setuptools wheel

      echo "~~~ cleaning"
      rm -rf dist

      echo "~~~ publishing"
      ./publish.sh

    label: publish
    branches: master
    agents:
      - type=native
    concurrency: 1
    concurrency_group: 'mysql-binlog-explorer-deploy'
